[package]
name = "github_actions_sandbox"
version = "0.1.0"
authors = ["y-sugino <ysgn0101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
